### ISSUE TITLE
Datasphere icons

### ISSUE THREAD

**Issue by yuan-thomas** [rsletta/sap_btp_icons_drawio_lib#3]
Any chance to have icons for Datasphere? Thanks.
https://discovery-center.cloud.sap/serviceCatalog/sap-datasphere?region=all

**Comment by yogananda-muthaiah** [comment]
@mauriciolauffer - New stylish icons and additional services as been added from last December 2022. you can pull the latest.

**Comment by mauriciolauffer** [comment]
The library has an [auto-update script](https://github.com/rsletta/sap_btp_icons_drawio_lib). Every time a new icon is published, the script updates the library, no need for manual work here 😊
Make sure to use `SAP_BTP_Service_Icons_latest.xml` to always get the latest icons.

![image](https://github.com/rsletta/sap_btp_icons_drawio_lib/assets/443888/8805bccd-8fad-41c0-9113-370c33f959af)

**Comment by yuan-thomas** [comment]
> The library has an [auto-update script](https://github.com/rsletta/sap_btp_icons_drawio_lib). Every time a new icon is published, the script updates the library, no need for manual work here 😊 Make sure to use `SAP_BTP_Service_Icons_latest.xml` to always get the latest icons.
> 
> ![image](https://user-images.githubusercontent.com/443888/264923126-8805bccd-8fad-41c0-9113-370c33f959af.png)

Ok I think I figured out what is going on.

I was using your Usage online section, by attaching the .xmls to URLs. I think 'SAP_BTP_Service_Icons_latest.xml' is missing in that URL so it didn't pick up that part.
